### ISSUE TITLE
Verify the pros and cons of using Zabbix and Nagios to monitor cloud.

### ISSUE THREAD

**Issue by minaliup** [fresearchgroup/IP-based-hardware-infrastructure-management-for-cloud#7]

**Comment by HarshKhatore** [comment]
A basic comparison between Nagios and Zabbix.
Verified.

[Nagios vs Zabbix.pdf](https://github.com/fresearchgroup/IP-based-hardware-infrastructure-management-for-cloud/files/1053868/Nagios.vs.Zabbix.pdf)
