### ISSUE TITLE
Nagios not listing the issues in SEL.

### ISSUE THREAD

**Issue by minaliup** [fresearchgroup/IP-based-hardware-infrastructure-management-for-cloud#8]

**Comment by mayank1010** [comment]
in the file /etc/nagios3/command.cfg
we are using the command : 
  **command_line  $USER1$/check_ipmi_sensor -H 10.129.36.161 -f $ARG1$** 
append -v at the last of this line to display the verbose output in the nagios which contains the sel issues.
So the new line looks like :
  **command_line  $USER1$/check_ipmi_sensor -H 10.129.36.161 -f $ARG1$ -v**
